[package]
name = "luminal"
version = "0.1.0"
edition = "2021"
description = "Deep learning at the speed of light."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
#default = ["cuda"]
cuda = ["dep:cudarc"]

[dependencies]
itertools = "0.11.0"
matrixmultiply = "0.3.7"
num-traits = "0.2.16"
petgraph = {path="./resources/petgraph"}
rand = "0.8.5"
strum = { version = "0.25.0", features = ["derive"] }
urlencoding = "2.1.2"
webbrowser = "0.8.10"
dyn-clone = "1.0.12"
cudarc = {version="0.9.13", optional=true}
safetensors = "0.3.1"

[dev-dependencies]
dfdx = "0.12.1"
