[package]
name = "luminal"
version = "0.1.0"
edition = "2021"
description = "Graph-based deep learning."
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
itertools = "0.11.0"
num-traits = "0.2.16"
petgraph = "0.6.3"
rand = "0.8.5"
strum = { version = "0.25.0", features = ["derive"] }
urlencoding = "2.1.2"
webbrowser = "0.8.10"

[dev-dependencies]
dfdx = "0.12.1"