[package]
name = "luminal"
version = "0.1.1"
edition = "2021"
description = "Deep learning at the speed of light."
license = "MIT OR Apache-2.0"

[features]
#default = ["cuda"]
cuda = ["dep:cudarc"]

[dependencies]
itertools = "0.11.0"
matrixmultiply = "0.3.7"
num-traits = "0.2.16"
petgraph = {path="./resources/petgraph"} # Literally only need this because the free_node field of the stable graph is private
rand = "0.8.5"
strum = { version = "0.25.0", features = ["derive"] }
urlencoding = "2.1.2"
webbrowser = "0.8.10"
dyn-clone = "1.0.12"
cudarc = {version="0.9.13", optional=true}
safetensors = "0.3.1"
memmap2 = "0.7.1"
half = "2.3.1"
tinyvec = "1.6.0"
term_size = "0.3.2"
colored = "2.0.4"

[dev-dependencies]
dfdx = "0.13"
rust_tokenizers = "8.1.0"
