[package]
name = "luminal_2"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
itertools = "0.14.0"
egglog = { git = "https://github.com/egraphs-good/egglog" }
petgraph = "0.8.1"
metal-rs = { version = "0.28.0", package = "metal" }
urlencoding = "2.1.3"
webbrowser = "1.0.4"
regex = "1.11.1"
serde_json = "1.0.140"
colored = "3.0.0"
