[package]
name = "luminal_symbolic"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tinyvec = "1.6.0"
rustc-hash = "1.1.0"
itertools = "0.11.0"